version: '3'

services:
  nginx-proxy:
    image: nginx-http-proxy #image from local file
    network_mode: host
    ports:
      - "80:80" #ports to open for running containers
  python-app:
    image: python-project #image from local file
    ports:
      - "5000:5000" #ports to open for running containers
    volumes:
      - ./:/app
  vue-app:
    image: vue-project #image from local file
    ports:
      - "8080:4000" #ports to open for running containers
    volumes:
      - ./:/app