version: '3'

services:
  python-app:
    image: python-project #image from local file
    container_name: python-project #running container name
    ports:
      - "5000:5000" #ports to open for running containers

  vue-app:
    image: vue-project #image from local file
    container_name: vue-project #running container name
    ports:
      - "8080:8080" #ports to open for running containers