apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-project
        image: 206080409328.dkr.ecr.us-east-1.amazonaws.com/python-project@sha256:f1b34de9044f10e1a15058dce3e1c11c908e69f43597de20ebc36be6cbe71905
        env:
        - name: ZONE_ID
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: ZONE_ID
        - name: CF_API_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: CF_API_KEY
        - name: CF_API_EMAIL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: CF_API_EMAIL
        - name: VUE_APP_PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: VUE_APP_PROXY_URL
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: LoadBalancer
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-proxy
        image: 206080409328.dkr.ecr.us-east-1.amazonaws.com/nginx-http-proxy@sha256:a828154c828723f729001da1834d0e106a9b2e467b75201df319edd2b624d562
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



---


apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-project
        image: 206080409328.dkr.ecr.us-east-1.amazonaws.com/vue-project@sha256:39fc51cd8e1083f9fc08620852ad4f84fe8e9af52c5cef239848670b1c2ae1af
        ports:
        - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: vue-service
spec:
  type: LoadBalancer
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080