apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      hostNetwork: true
      containers:
      - name: python-project
        image: public.ecr.aws/l1z2o5a3/python-project
        env:
        - name: ZONE_ID
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: ZONE_ID
        - name: CF_API_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: CF_API_KEY
        - name: CF_API_EMAIL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: CF_API_EMAIL
        - name: VUE_APP_PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: VUE_APP_PROXY_URL
        ports:
        - containerPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - name: nginx-proxy
        image: public.ecr.aws/l1z2o5a3/nginx-http-proxy
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002



---


apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      hostNetwork: true
      containers:
      - name: vue-project
        image: public.ecr.aws/l1z2o5a3/vue-project
        env:
        - name: ZONE_ID
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: VUE_APP_PROXY_URL
        ports:
        - containerPort: 8080


---


apiVersion: v1
kind: Service
metadata:
  name: vue-service
spec:
  type: NodePort
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003