apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /app
            pathType: Exact
            backend:
              service:
                name: vue-service
                port:
                  number: 80
          - path: /proxy
            pathType: Exact
            backend:
              service:
                name: python-service
                port:
                  number: 5000