version: '3'

services:
  vue-app:
    image: vue-project #image from local file
    container_name: vue-project #running container name
    ports:
      - "8080:4000" #ports to open for running containers
    volumes:
      - ./:/app